### ISSUE TITLE
BindEdgesToSuperview crash on negative inset

### ISSUE THREAD

**Issue by insightmind** [Flinesoft/HandyUIKit#11]
![screen shot 2019-01-13 at 9 01 08 pm](https://user-images.githubusercontent.com/24965150/51090054-78191400-1776-11e9-8180-2fe8f1c9da70.png)

The new unreleased implementation of `bindEdgesToSuperview(_ inset: UIEdgeInset)` crashes on negative insets.
So for the actual value of the inset should be put in parentheses in the constraint format.

**Comment by Jeehut** [comment]
Feel free to post a PR, should be a no-brainer.
