### ISSUE TITLE
Use Double.pi instead of deprecated M_PI

### ISSUE THREAD

**Issue by pepejeria** [Flinesoft/HandyUIKit#2]
Description says it all, use Double.pi instead of deprecated M_PI to get rid of warnings.

**Comment by Jeehut** [comment]
Thank you @pepejeria for getting back to me about the warnings. I actually had already fixed them in 186ac6715914f48f069441e2e6194785ad2d45e2 some time ago, but I didn't make a release. Just did that. Should be solved in version 1.4.1.

**Comment by pepejeria** [comment]
Thanks
