### ISSUE TITLE
Bug on superscript

### ISSUE THREAD

**Issue by ghost** [Flinesoft/HandyUIKit#6]
"x^{2}" - works as expected but reversing it "^{2}x" would result in the whole string being superscripted. A work-around is adding a space in front of the string " ^{2}x" and the result is ok but needles to say it is a useless drag removing the space from a NSMutableAttributedString. 

Thank you

**Comment by Jeehut** [comment]
Hi @EmyXOR, thank you for reporting this error and sorry for answering so late.

I just checked this by adding the following lines to the `UsageExamples.playground` file:

```swift
"^{2}x^{3}".superscripted(font: .systemFont(ofSize: 12))
"^{2}x".superscripted(font: .systemFont(ofSize: 12))
```

These were the results, so it seems everything worked as expected:

![bildschirmfoto 2018-07-09 um 16 31 15](https://user-images.githubusercontent.com/6942160/42456569-8c822adc-8395-11e8-907f-9f5e2f83b3f4.png)
![bildschirmfoto 2018-07-09 um 16 31 09](https://user-images.githubusercontent.com/6942160/42456570-8ca43f14-8395-11e8-8347-b3bc9bb6efda.png)

What version of HandyUIKit are you using and what version of Xcode & Swift are you using? Also, what is your deployment target and platform?

**Comment by Jeehut** [comment]
Closing this due to irreproducability & inactivity.
