### ISSUE TITLE
HandyUIKit is not supported for Xcode 10

### ISSUE THREAD

**Issue by mohdsafadsaal** [Flinesoft/HandyUIKit#7]
Hi ,

We updated our xcode version to xcode 10. Its throwing an error in UIViewExtension file.

**Comment by pepejeria** [comment]
@Dschee  Do you have any plans to release the Xcode 10 branch soon? Can I help somehow?

**Comment by Jeehut** [comment]
Ah, sorry, forgot this. Gonna release a new version sometime today (CEST).

**Comment by pepejeria** [comment]
That is great to hear. Thanks!

**Comment by Jeehut** [comment]
@pepejeria I just released version 1.8.0 with Swift 4.2 & Xcode 10.0 support – this should be solved now. See Release Notes [here](https://github.com/Flinesoft/HandyUIKit/releases/tag/1.8.0).

**Comment by pepejeria** [comment]
Thanks. Cocoapods still gives me 1.7.3 though.

**Comment by Jeehut** [comment]
Right you are, there was an issue with the Podspec file since I restructured the code files. But I fixed it now and made the release for CocoaPods as well!

**Comment by pepejeria** [comment]
Cool, works now. Thanks!
